version: "3.9"

networks:
    laravel:
        name: laravel

services:

    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        depends_on:
            - php
            - mariadb
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./adminlte-system:/var/www/html
        networks:
            - laravel

#    apache:
#        build:
#            context: .
#            dockerfile: apache.dockerfile
#        container_name: apache
#        ports:
#            - 80:80
#            - 443:443
#        volumes:
#            - ./adminlte-system:/var/www/html
#        networks:
#            - virtual-fair

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./adminlte-system:/var/www/html
        networks:
            - laravel

    mariadb:
        image: mariadb
        platform: linux/amd64
        container_name: mariadb
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laraveldb
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./adminlte-system:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel

    artisan:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: artisan
        volumes:
            - ./adminlte-system:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['php', 'artisan']
        networks:
            - laravel

    npm:
        image: node:current-alpine
        container_name: npm
        volumes:
            - ./adminlte-system:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel







